name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server:  ${{ secrets.GITF }}
          username: ${{ secrets.GITU }}
          password: ${{ secrets.GITP }}
          server-dir: beda/
          log-level: verbose
          protocol: ftps
          port: 21
          dry-run: true
