name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server:  ${{ secrets.GITF }}
          ftp-username: ${{ secrets.GITU }}
          ftp-password: ${{ secrets.GITP }}
          local-dir: ./
