name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code FROM REPO
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server:  eimbox.com
          username: eimbox
          password: ${{ secrets.GITP }}
          server-dir: ./beda/keda/
          log-level: verbose
          state-name: .ftp-deploy-sync-state.json
          port: 21
          dry-run: false
          timeout: 60000
